### ISSUE TITLE
Redesign of single-track pages

### ISSUE THREAD

**Issue by theshillito** [very-scary-scenario/nkd.su#184]
As an extension of https://github.com/very-scary-scenario/nkd.su/issues/129 I think perhaps an overall redesign of the individual track pages would be good. Considering I talked about composers on the show at the weekend, and we have composer (among other data) in the library anyway, why don't we add this to the track pages? Also, we get album artwork anyway, so why not show them on the expanded single track view? 

Enjoy this awful mockup in paint!

![image](https://user-images.githubusercontent.com/1828418/102768829-aa2b4b80-4379-11eb-8882-ce486eda0f9a.png)

(this might be a place to put links to buy the tracks too where available, with or without affiliate stuff https://github.com/very-scary-scenario/nkd.su/issues/72 )

**Comment by euricaeris** [comment]
I'd also love to see us pulling the year of release into this as well, if the song has it in its meta. Honestly happy to go through the library and add years gradually if we could slot 'em in.

**Comment by theshillito** [comment]
An example output for a single track in the library is as follows:

```
<dict>
	<key>Track ID</key><integer>10788</integer>
	<key>Name</key><string>Serendipity (Flip Flappers OP)</string>
	<key>Artist</key><string>ZAQ</string>
	<key>Composer</key><string>ZAQ</string>
	<key>Album</key><string>Serendipity</string>
	<key>Genre</key><string>Anime</string>
	<key>Kind</key><string>MPEG audio file</string>
	<key>Size</key><integer>11609456</integer>
	<key>Total Time</key><integer>285544</integer>
	<key>Track Number</key><integer>1</integer>
	<key>Track Count</key><integer>4</integer>
	<key>Year</key><integer>2016</integer>
	<key>Date Modified</key><date>2017-10-16T16:47:30Z</date>
	<key>Date Added</key><date>2017-02-11T18:46:44Z</date>
	<key>Bit Rate</key><integer>320</integer>
	<key>Sample Rate</key><integer>44100</integer>
	<key>Comments</key><string>ExactAudioCopy v1.1</string>
	<key>Skip Count</key><integer>1</integer>
	<key>Skip Date</key><date>2017-02-25T12:42:21Z</date>
	<key>Rating</key><integer>100</integer>
	<key>Album Rating</key><integer>100</integer>
	<key>Album Rating Computed</key><true/>
	<key>Artwork Count</key><integer>1</integer>
	<key>Persistent ID</key><string>2926CB325B08C76C</string>
	<key>Track Type</key><string>File</string>
	<key>Location</key><string>file://localhost/Users/peter/Music/iTunes/iTunes%20Music/Music/ZAQ/Serendipity/01%20Serendipity%20(Flip%20Flappers%20OP).mp3</string>
	<key>File Folder Count</key><integer>5</integer>
	<key>Library Folder Count</key><integer>1</integer>
</dict>
```

So year and composer are easy as they're always included if they have a value set, record label isn't included as it's in a tag not exported by iTunes, but that's not that important and probably not that interesting. Comments, however, are included, so we could always start putting things in there, rather than just ExactAudioCopy or wherever the track was _obtained_ from.

**Comment by theshillito** [comment]
Since this issue was made, years and composers are now present on all tracks. The tagging system mentioned on #148 would also add additional data to display on individual tracks pages that wouldn't be shown anywhere else.

**Comment by colons** [comment]
composer and year of release are now present on track pages, which i think makes this resolvable. if you have other stuff to surface, please make different issues about it. album art is its own bucket of nightmares
