### ISSUE TITLE
80s Roulette!

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/nkd.su#193]
Tbf it'd probably be rad if we could pick a decade and roulette with it, but 80s roulette is important.

**Comment by euricaeris** [comment]
![gib](https://user-images.githubusercontent.com/2502449/118317495-08ef8e00-b4f0-11eb-9ca3-e97ea2e9be2e.png)

Something like this that reveals the decades when decade roulette is selected?

**Comment by theshillito** [comment]
Should be 80's by default

**Comment by homsar** [comment]
FWIW the functionality to have sub-roulettes is in #163 so potentially could be lifted from there.
