### ISSUE TITLE
Surfacing content from protected tweets

### ISSUE THREAD

**Issue by homsar** [very-scary-scenario/nkd.su#195]
Currently nkdsu shows both votes and vote comments from protected accounts that it follows, including to non-logged in users.

Twitter’s API policy states “A protected account’s content is only available to people who have been approved by the owner to follow that account. So, if you run a service that accesses protected accounts, you may only do so to serve such content to the specific people with permission to view that content”.

This would minimally imply that vote comments should be hidden except to logged in users who follow the protected user (or site admins, who could be considered to be logging in as nkdsu). (This also raises questions about reading vote comments on air…)

One could also take the viewpoint that showing the fact that a particular private account has voted at all is private information. That would necessitate replacing a private user’s icon and profile link with a placeholder for non-logged in users and logged-in users who don’t follow the private account. The user’s profile would then also need to be not accessible to the same set of users.

**Comment by theshillito** [comment]
This will no longer happen due to removal of Twitter-based requesting
