### ISSUE TITLE
Link to various anime list websites from corresponding anime pages on nkd.su

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/nkd.su#227]
It'd be neat if we link to an anime's corresponding page on the various anime list websites (anilist, MAL, anidb etc.). This would be neat for people that want to add shows to their 'to watch' lists after hearing a banger/discussion on the show, but also the more we add older, JP-only shows, the more it'll help to just show people what on earth the shows even are.

So as an example, the nkd.su page for Choudenji Robo Combattler V (https://nkd.su/anime/Choudenji%20Robo%20Combattler%20V/) could point to these pages:

- https://anilist.co/anime/1068/Chou-Denji-Robo-Combattler-V
- https://myanimelist.net/anime/1068/Chou_Denji_Robo_Combattler_V
- https://anidb.net/anime/1814

I don't know how feasible this even is to do automatically, and there's probably some fun edge cases to have to handle (some specials/OVAs, batches of movies, Hoshiiro Girldrop etc) but I think it'd be a neat feature if we can make it work. You could even pull in a synopsis (and credit whichever site it's pulled from) in the same way, if that's something of interest.

**Comment by theshillito** [comment]
I believe this has been a plan for a while as it would then allow us to use an API to look up English/Japanese romaji/Japanese kanji names and have it be toggleable.

**Comment by theshillito** [comment]
This has been implemented.
