### ISSUE TITLE
Put a red dot/alert over the menu button for elves/higher when there are new requests/meta to look at

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/nkd.su#266]
As you're poking about with the menu, this would stop me from clicking on it to check as often as I do.

**Comment by colons** [comment]
how are you wanting to define "new" here? should i keep track of which elf has been shown each request, or can i just show the dot when there are ones that have not been claimed? or something else?

**Comment by euricaeris** [comment]
I don't think claiming would work here as there are currently two old requests that are unclaimed, and can't be claimed as the songs they're requesting were not released - we'd need some kind of 'archive' button if you were tracking it that way.

If an elf has seen all current requests makes more sense to me, but turning the alert off if the new request has been claimed/completed by another elf.

**Comment by colons** [comment]
(from discussions) i think the best way to do this is with some kind of "elf shelf" where an elf can express that a request cannot be fulfilled, at least for the moment
