### ISSUE TITLE
An 'upcoming' section of the site for admin/elves for new songs that are currently hidden

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/nkd.su#270]
A page that is visually identical to the new tracks page, but without voting capability. I think this could be useful mostly because it's a really good way to see if we're introducing any metadata errors. 

Typically when we add songs, I run through every link to make sure they go where we expect them to go when they go live. While it's not common, there are occasions where mistakes slip through the cracks, mostly because it's much easier to spot mistakes on the new tracks page. Having an 'upcoming' page would mean admins/elves can check over new tracks and make corrections where needed, before they go out to voters.

**Comment by theshillito** [comment]
I'm not sure this will do what you're hoping as the time between new tracks being hidden and then being visible on the site is often at most a few minutes. The situation with Suzume isn't the norm. There's also a lot of hidden tracks for other reasons (swear-free placeholder, duplicates, accidentally played b-sides, etc) although there's been some discussion of adding "super hidden".

**Comment by euricaeris** [comment]
Fair enough - definitely not worth it if it also means changing how things work when we can get things fixed pretty sharpish lol
