### ISSUE TITLE
Make it clear when the show starts in the site header

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/nkd.su#274]
Given how much I keep seeing nkd.su song pages while doing searches online, I think it's important to put the start time of the show on the homepage. Currently you can't find it anywhere unless you've hit nekodesu.radio. 

Maybe a simple reference to the time/timezone:
![banner1](https://github.com/very-scary-scenario/nkd.su/assets/2502449/1a9c80dc-541b-433a-b8b8-74024d8cbe59)

...or just a countdown, because timezones are hard:

![banner2](https://github.com/very-scary-scenario/nkd.su/assets/2502449/85d3635c-032a-4b1d-95d7-244cefeffbe0)

**Comment by theshillito** [comment]
This should also be changed to "next live Neko Desu" with the repeats starting in a couple weeks

**Comment by theshillito** [comment]
Also also, should say UK time instead of GMT unless we put time zone detection in etc cos we're not in GMT right now

**Comment by colons** [comment]
resolved across bdc046481071c693a825417c94963dbc9faae46c...adeaeb27100783842ad811492804322da988283c
