### ISSUE TITLE
The voting experience is not especially reassuring

### ISSUE THREAD

**Issue by colons** [very-scary-scenario/nkd.su#45]
…especially if you're voting for a bunch of tracks at once. The intent window doesn't really inspire confidence that you're doing what you want to be doing.

![voting](http://colons.co/voting.png)

Proposed solution: frame the intent with something explaining what's about to happen (and that you can personalise your vote).

**Comment by theshillito** [comment]
Requesting no longer uses tweets, so this is no longer a concern.
